name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if you're using that branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version if needed

    - name: Install dependencies
      run: npm install # Optional step if your project requires dependencies

    - name: Build the site
      run: npm run build # Optional step if your project has a build process

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public # Replace 'public' with your folder name
